const Forncedor = require('../controller/cadastarFornecedor')
const Produtos = require('../controller/CadastrarProduto')
const Forncedoress = require('../controller/GetForncedores')
const deleteProduct = require('../controller/DeleteProduto')
const getProdutos = require('../controller/GetProdutos')
const Usuario = require('../controller/LoginUser')
const excel = require('../controller/Relatorio')
const Senha = require('../controller/TrocarSenhaUser')
const ProdutosEdit = require('../controller/editProduto')
const Movimentacoes = require('../controller/movimentacoes')
const movimentacoesGet = require('../controller/Getmovimentacoes')
const getVendas = require('../controller/GetVendas')
const apii = require('express').Router()
apii.patch("/atualizarSenha", Senha.router)
apii.patch('/atuaizarProduto', ProdutosEdit.router)
apii.patch('/movimentacoes',Movimentacoes.router)
apii.get('/getVendas', getVendas.getMovimentacoes)
apii.delete("/deleteProduto/:id", deleteProduct.router)
apii.get('/getMovimentacoes', movimentacoesGet.getMovimentacoes)
apii.post('/post/product',Produtos.routerProducy)
apii.get('/produtos', getProdutos.listProduct)
apii.post('/forncedores', Forncedor.RouterFor)
apii.get('/forncedores', Forncedoress.selectFormnecores)
apii.post('/getrelatorios', excel.Router)
apii.use(Usuario.ValideJwt)
apii.post('/users', Usuario.loginUser)

module.exports = apii